# Generated by Django 4.2 on 2023-04-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('image_url', models.URLField(null=True)),
                ('same_ingredients', models.IntegerField(default=0)),
                ('dishType', models.CharField(max_length=64, null=True)),
                ('servingSize', models.CharField(max_length=64, null=True)),
                ('mealUrl', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealPlanner.meals', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=64)),
                ('ingredient', models.CharField(max_length=64)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealPlanner.meals')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
