# Generated by Django 4.2 on 2023-04-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='image_url',
            new_name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='dishType',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='same_ingredients',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='servingSize',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(default='count', max_length=64),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealPlanner.meals')),
            ],
        ),
    ]
